/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardtestRouteImport } from './routes/dashboardtest'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiCronRunMonitoringRouteImport } from './routes/api/cron/run-monitoring'
import { Route as ApiWebhooksPaddleRouteImport } from './routes/api/webhooks/paddle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardtestRoute = DashboardtestRouteImport.update({
  id: '/dashboardtest',
  path: '/dashboardtest',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRunMonitoringRoute = ApiCronRunMonitoringRouteImport.update({
  id: '/api/cron/run-monitoring',
  path: '/api/cron/run-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksPaddleRoute = ApiWebhooksPaddleRouteImport.update({
  id: '/api/webhooks/paddle',
  path: '/api/webhooks/paddle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/dashboardtest': typeof DashboardtestRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/refund': typeof RefundRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/api/cron/run-monitoring': typeof ApiCronRunMonitoringRoute
  '/api/webhooks/paddle': typeof ApiWebhooksPaddleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/dashboardtest': typeof DashboardtestRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/refund': typeof RefundRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/api/cron/run-monitoring': typeof ApiCronRunMonitoringRoute
  '/api/webhooks/paddle': typeof ApiWebhooksPaddleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/dashboardtest': typeof DashboardtestRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/refund': typeof RefundRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/api/cron/run-monitoring': typeof ApiCronRunMonitoringRoute
  '/api/webhooks/paddle': typeof ApiWebhooksPaddleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboardtest'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/refund'
    | '/signup'
    | '/terms'
    | '/api/cron/run-monitoring'
    | '/api/webhooks/paddle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboardtest'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/refund'
    | '/signup'
    | '/terms'
    | '/api/cron/run-monitoring'
    | '/api/webhooks/paddle'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboardtest'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/refund'
    | '/signup'
    | '/terms'
    | '/api/cron/run-monitoring'
    | '/api/webhooks/paddle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DashboardtestRoute: typeof DashboardtestRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RefundRoute: typeof RefundRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  ApiCronRunMonitoringRoute: typeof ApiCronRunMonitoringRoute
  ApiWebhooksPaddleRoute: typeof ApiWebhooksPaddleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboardtest': {
      id: '/dashboardtest'
      path: '/dashboardtest'
      fullPath: '/dashboardtest'
      preLoaderRoute: typeof DashboardtestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/run-monitoring': {
      id: '/api/cron/run-monitoring'
      path: '/api/cron/run-monitoring'
      fullPath: '/api/cron/run-monitoring'
      preLoaderRoute: typeof ApiCronRunMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/paddle': {
      id: '/api/webhooks/paddle'
      path: '/api/webhooks/paddle'
      fullPath: '/api/webhooks/paddle'
      preLoaderRoute: typeof ApiWebhooksPaddleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DashboardtestRoute: DashboardtestRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RefundRoute: RefundRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  ApiCronRunMonitoringRoute: ApiCronRunMonitoringRoute,
  ApiWebhooksPaddleRoute: ApiWebhooksPaddleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
